# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: polaris

steps:
  - task: SynopsysSecurityScan@1.6.0
    displayName: 'Polaris Scan'
    condition: not(eq(variables['Build.Reason'], 'PullRequest'))
    inputs:
      BRIDGE_POLARIS_SERVERURL: $(POLARIS_SERVER_URL)
      BRIDGE_POLARIS_ACCESSTOKEN: $(POLARIS_ACCESS_TOKEN)
      BRIDGE_POLARIS_APPLICATION_NAME: 'Synopsys_github_demo_repo'
      BRIDGE_POLARIS_PROJECT_NAME: 'WebGoat'
      BRIDGE_POLARIS_ASSESSMENT_TYPES: 'SCA,SAST' # Accepts Multiple Values
