name: Synopsys Security Testing (Polaris SAST+SCA)

on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:

jobs:      
  build:
    runs-on: ubuntu-latest
    steps:      
      -   uses: actions/checkout@v3
      -   name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
              distribution: 'temurin'
              java-version: 17
              architecture: x64
      -   name: Cache Maven packages
          uses: actions/cache@v3.2.5
          with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2-
      -   name: Build with Maven
          run: mvn --no-transfer-progress clean compile -DskipTests


      -   name: Polaris Scan
          uses: synopsys-sig/synopsys-action@v1.8.0
          with:
            ### SCANNING: Required fields
            polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
            polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
            polaris_application_name: "APAC-SG-github-demo"
            polaris_project_name: "WebGoat"
            polaris_assessment_types: "SCA,SAST"
            
      -   name: Polaris PR Scan
          if: ${{ github.event_name == 'pull_request' }}
          uses: synopsys-sig/synopsys-action@v1.8.0
          with:
            ### SCANNING: Required fields
            polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
            polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
            polaris_application_name: "APAC-SG-github-demo"
            polaris_project_name: "mini-JS"
            polaris_assessment_types: "SCA,SAST"
            
            ### Below configuration is used to enable feedback from Polaris security testing as pull request comment
            polaris_prComment_enabled: true 
            github_token: ${{ secrets.GITHUB_TOKEN }} 


        
