name: Synopsys Security Testing (Polaris SAST+SCA)

on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:

jobs:      
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: install dependency
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install --no-audit --no-fund --silent

      - name: Polaris Scan
        uses: synopsys-sig/synopsys-action@v1.8.0
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_application_name: "APAC-SG-github-demo"
          polaris_project_name: "WebGoat"
          polaris_assessment_types: "SCA,SAST"
          polaris_prComment_enabled: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

          ### SARIF report generation and upload to GitHub Adavanced Security Tab
          polaris_reports_sarif_create: true  
          polaris_reports_sarif_groupSCAIssues: true 
          # polaris_reports_sarif_issue_types: 'SCA, SAST'
          polaris_upload_sarif_report: true



        
