name: Synopsys Security Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  DETECT_PROJECT_NAME: shichao-GH-mini
  DETECT_PROJECT_VERSION_NAME: ${{ github.sha }}
  DETECT_TOOLS: DETECTOR
  DETECT_TIMEOUT: 3000
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: install dependency
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install --no-audit --no-fund --silent
      
      - name: Black Duck (Rapid scan)
        if: ${{ github.event_name == 'pull_request' }}
        uses: synopsys-sig/detect-action@v1.2.0
        with:
          scan-mode: RAPID
          blackduck_automation_prcomment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 8.9.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}

      - name: Black Duck (Full scan)
        if: ${{ github.event_name != 'pull_request' }}
        uses: synopsys-sig/detect-action@v1.2.0
        with:
          scan-mode: INTELLIGENT
          fail-on-all-policy-severities: true
          
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 8.9.0
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
