name: Synopsys Security Testing

on:  
  workflow_dispatch:
  pull_request:
  
env:
  DETECT_PROJECT_NAME: shichao-GH-mini
  DETECT_PROJECT_VERSION_NAME: ${{ github.sha }}
  DETECT_TOOLS: DETECTOR
  DETECT_TIMEOUT: 3000
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: install dependency
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install --no-audit --no-fund --silent

      - name: Synopsys Action
        uses: synopsys-sig/synopsys-action@v1.1.0
        with:
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          
          blackduck_scan_full: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          blackduck_automation_fixpr: true
          blackduck_scan_failure_severities: "ALL"
          blackduck_automation_prcomment: true
        
      
   #   - name: Synopsys Action
    #    uses: synopsys-sig/synopsys-action@v1.1.0
     #   with:
      #    polaris_serverUrl: ${{ secrets.POLARIS_SEVER_URL }}
       #   polaris_accessToken: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        #  polaris_application_name: "APAC-SG-github-demo2"
         # polaris_project_name: "miniJS"
          #polaris_assessment_types: "SCA,SAST"

          

        
