name: Synopsys Security Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  DETECT_PROJECT_NAME: shichao-GH-mini
  DETECT_PROJECT_VERSION_NAME: ${{ github.sha }}
  DETECT_TOOLS: DETECTOR
  DETECT_TIMEOUT: 3000
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: install dependency
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install --no-audit --no-fund --silent

      - name: Black Duck (Full scan)
        uses: synopsys-sig/detect-action@main
        with:
          blackduck_scan_full: true
          blackduck_scan_failure_severities: "ALL"
          
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.12.0
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          
          
